version: "3.9"

services:
  db:
    image: postgres:13
    container_name: kivitendo-db
    environment:
      POSTGRES_USER: kivitendo
      POSTGRES_PASSWORD: kivitendo
      POSTGRES_DB: kivitendo
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - kivitendo-net

  app:
    build: .
    container_name: kivitendo-erp
    depends_on:
      - db
    ports:
      - "82:80"
    environment:
      DB_HOST: db
      DB_USER: kivitendo
      DB_PASSWORD: kivitendo
      DB_NAME: kivitendo

    volumes:
      - webdav:/opt/kivitendo-erp/webdav
      - ./druckvorlagen:/opt/kivitendo-erp/templates/cvs

    networks:
      - kivitendo-net
    # Uncomment the following if you want the container to restart automatically
    # restart: always

volumes:
  db_data:
  webdav:

networks:
  kivitendo-net:
    driver: bridge